In [16]:
import pandas as pd

In [2]:
cd Datasets

C:\Users\Utomi Ogbe\Desktop\datatalks 2024\3_mage\Datasets

In [3]:
taxi_dtypes = {
        'VendorID': pd.Int64Dtype(),
        'passenger_count': pd.Int64Dtype(),
        'trip_distance': float,
        'RatecodeID': pd.Int64Dtype(),
        'store_and_fwd_flag': str,
        'PULocationID': pd.Int64Dtype(),
        'DOLocationID': pd.Int64Dtype(),
        'payment_type': pd.Int64Dtype(),
        'fare_amount': float,
        'extra': float,
        'mta_tax': float,
        'tip_amount': float,
        'tolls_amount': float,
        'improvement_surcharge': float,
        'total_amount': float,
        'congestion_surcharge': float 
    }

parse_dates = ['lpep_pickup_datetime', 'lpep_dropoff_datetime']

In [4]:
greentrip_data_2020_10 = pd.read_csv('C:/Users/Utomi Ogbe/Desktop/datatalks 2024/3_mage/Datasets/green_tripdata_2020-10.csv.gz', sep=",", compression="gzip", dtype=taxi_dtypes, parse_dates=parse_dates)
greentrip_data_2020_11 = pd.read_csv('C:/Users/Utomi Ogbe/Desktop/datatalks 2024/3_mage/Datasets/green_tripdata_2020-11.csv.gz', sep=",", compression="gzip", dtype=taxi_dtypes, parse_dates=parse_dates)
greentrip_data_2020_12 = pd.read_csv('C:/Users/Utomi Ogbe/Desktop/datatalks 2024/3_mage/Datasets/green_tripdata_2020-12.csv.gz', sep=",", compression="gzip", dtype=taxi_dtypes, parse_dates=parse_dates)

In [5]:
greentrip_data = pd.concat([greentrip_data_2020_10, greentrip_data_2020_11, greentrip_data_2020_12])

In [6]:
greentrip_data.shape

(266855, 20)

In [7]:
greentrip_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 266855 entries, 0 to 83129
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               147393 non-null  Int64
 1   lpep_pickup_datetime   266855 non-null  datetime64[ns]
 2   lpep_dropoff_datetime  266855 non-null  datetime64[ns]
 3   store_and_fwd_flag     147393 non-null  object
 4   RatecodeID             147393 non-null  Int64
 5   PULocationID           266855 non-null  Int64
 6   DOLocationID           266855 non-null  Int64
 7   passenger_count        147393 non-null  Int64
 8   trip_distance          266855 non-null  float64
 9   fare_amount            266855 non-null  float64
 10  extra                  266855 non-null  float64
 11  mta_tax                266855 non-null  float64
 12  tip_amount             266855 non-null  float64
 13  tolls_amount           266855 non-null  float64
 14  ehail_fee              0 non-null       float64
 15  improvement_surcharge  266855 non-null  float64
 16  total_amount           266855 non-null  float64
 17  payment_type           147393 non-null  Int64
 18  trip_type              147393 non-null  float64
 19  congestion_surcharge   147393 non-null  float64
dtypes: Int64(6), datetime64[ns](2), float64(11), object(1)
memory usage: 44.3+ MB

In [8]:
greentrip_data.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2020-10-01 00:31:19,2020-10-01 00:34:55,N,1,7,7,1,0.79,5.0,0.5,0.5,1.58,0.0,NaN,0.3,7.88,1,1.0,0.0
1,2,2020-10-01 00:42:12,2020-10-01 00:43:51,N,1,179,7,1,0.50,4.0,0.5,0.5,0.00,0.0,NaN,0.3,5.30,2,1.0,0.0
2,2,2020-10-01 00:53:09,2020-10-01 00:55:39,N,1,179,223,1,0.60,4.0,0.5,0.5,1.06,0.0,NaN,0.3,6.36,1,1.0,0.0
3,1,2020-10-01 00:12:29,2020-10-01 00:20:08,N,1,134,216,2,4.40,13.5,0.5,0.5,0.00,0.0,NaN,0.3,14.80,2,1.0,0.0
4,1,2020-10-01 00:32:38,2020-10-01 00:43:02,N,1,82,7,1,2.90,10.5,0.5,0.5,0.00,0.0,NaN,0.3,11.80,2,1.0,0.0

In [9]:
greentrip_data = greentrip_data[(greentrip_data['passenger_count'] > 0) & (greentrip_data['trip_distance'] > 0)]

In [10]:
greentrip_data.shape

(139370, 20)

In [11]:
greentrip_data['lpep_pickup_date'] = greentrip_data['lpep_pickup_datetime'].dt.date
# greentrip_data['lpep_dropoff_datetime'] = greentrip_data['lpep_pickup_datetime'].dt.date

In [12]:
greentrip_data.columns = (greentrip_data.columns
                    .str.replace(' ', '_')
                    .str.lower()
    )

greentrip_data = greentrip_data.rename(columns= {'vendorid':'vendor_id', 
                                                 'ratecodeid': 'ratecode_id',
                                                'pulocationid': 'pulocation_id',
                                                'dolocationid': 'dolocation_id'})

In [13]:
greentrip_data.vendor_id.unique()

<IntegerArray>
[2, 1]
Length: 2, dtype: Int64

In [14]:
greentrip_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 139370 entries, 0 to 46291
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   vendor_id              139370 non-null  Int64
 1   lpep_pickup_datetime   139370 non-null  datetime64[ns]
 2   lpep_dropoff_datetime  139370 non-null  datetime64[ns]
 3   store_and_fwd_flag     139370 non-null  object
 4   ratecode_id            139370 non-null  Int64
 5   pulocation_id          139370 non-null  Int64
 6   dolocation_id          139370 non-null  Int64
 7   passenger_count        139370 non-null  Int64
 8   trip_distance          139370 non-null  float64
 9   fare_amount            139370 non-null  float64
 10  extra                  139370 non-null  float64
 11  mta_tax                139370 non-null  float64
 12  tip_amount             139370 non-null  float64
 13  tolls_amount           139370 non-null  float64
 14  ehail_fee              0 non-null       float64
 15  improvement_surcharge  139370 non-null  float64
 16  total_amount           139370 non-null  float64
 17  payment_type           139370 non-null  Int64
 18  trip_type              139370 non-null  float64
 19  congestion_surcharge   139370 non-null  float64
 20  lpep_pickup_date       139370 non-null  object
dtypes: Int64(6), datetime64[ns](2), float64(11), object(2)
memory usage: 24.2+ MB

In [15]:
# assert greentrip_data.columns.isin(['vendor_id']), 'There is no vendor_id column'

assert 'vendor_id' in greentrip_data.columns, 'There is no vendor_id column'
assert greentrip_data['passenger_count'].isin([0]).sum() == 0, 'There are rides with zero passengers'
assert greentrip_data['trip_distance'].isin([0]).sum() == 0, 'There are rides with zero distance'

In [19]:
greentrip_data.groupby(['lpep_pickup_date']).max(['tip_amount'])

,vendor_id,ratecode_id,pulocation_id,dolocation_id,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
lpep_pickup_date,,,,,,,,,,,,,,,,,
2009-01-01,2,1,61,97,1,2.81,11.5,0.00,0.5,0.00,0.00,NaN,0.3,12.30,2,1.0,0.00
2020-09-30,2,5,260,260,1,0.41,20.0,0.50,0.5,4.06,0.00,NaN,0.3,24.36,2,2.0,0.00
2020-10-01,2,5,265,265,6,75.70,88.5,4.50,0.5,40.00,13.75,NaN,0.3,118.50,4,2.0,2.75
2020-10-02,2,5,265,265,6,44.66,146.5,4.50,0.5,111.11,13.75,NaN,0.3,162.05,4,2.0,2.75
2020-10-03,2,5,265,265,6,32.70,100.0,3.75,0.5,24.00,25.99,NaN,0.3,104.56,4,2.0,2.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-28,2,5,265,265,6,49.16,238.0,4.50,0.5,15.86,12.24,NaN,0.3,240.00,4,2.0,2.75
2020-12-29,2,5,265,265,6,67.86,222.0,4.50,0.5,42.21,27.50,NaN,0.3,253.26,4,2.0,2.75
2020-12-30,2,5,265,265,6,35.12,203.0,3.75,0.5,20.06,13.75,NaN,0.3,205.00,4,2.0,2.75
2020-12-31,2,5,265,265,6,40.68,188.0,3.75,0.5,30.00,13.75,NaN,0.3,200.00,3,2.0,2.75
2021-01-01,2,1,37,217,1,1.59,8.0,0.50,0.5,0.00,0.00,NaN,0.3,9.30,2,1.0,0.00